### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by MooreManor** [hxwork/H2ONet_Pytorch#1]
Hello! @hxwork 

Do you have any plans to release the H2Onet training code or demo code in the future?

**Comment by hxwork** [comment]
Hi,

Yes. We are planning to release our code recently. Maybe within 1-2 months.

Best,
XH

**Comment by MooreManor** [comment]
@hxwork 

Thanks for your in-time reply! I have another question. At what time can we see the paper of H2Onet?

**Comment by hxwork** [comment]
Thanks for your interest. We have released our paper in this repo, and you can download it now.
