### ISSUE TITLE
Checkpoint and inference code

### ISSUE THREAD

**Issue by huytuong010101** [hxwork/H2ONet_Pytorch#2]
Hi @hxwork 
Thanks for perfect project, I really interested in you research, especially use multi-frame to inprove hand estimation.
Do you have plan to public checkpoint and inference code in multi-frame?
Look forward to you reply...

**Comment by hxwork** [comment]
Hi,

Thanks for your interest! I apologize that the remaining code should have been released earlier but I am working on another project. It will be released in November.

**Comment by hxwork** [comment]
Hi,

We have updated the code. You can download the pre-trained model on the DexYCB dataset and test it by `test.py` script.
