### ISSUE TITLE
Occlusion label preparation code for the HO3D dataset

### ISSUE THREAD

**Issue by delaprada** [hxwork/H2ONet_Pytorch#3]
Thank you for providing such a good work!

I am very interested in the occlusion label preparation. May I ask do you plan to update the occlusion label preparation code for HO3D dataset?

It seems that code would be similar to DEX_YCB dataset?

**Comment by hxwork** [comment]
Hi,

Thanks for your focus! Actually, they should be similar only with a little modification. You can write the code for HO3D based on the current DexYCB version. Or, you can wait for me to release the remaining code in November. Hope you can understand.

**Comment by delaprada** [comment]
Thank you very much for your reply!
